name: So Whats Bitcoin?
markdown: redcarpet
pygments: true

exclude:  [CNAME, Gemfile, Gemfile.lock]

relative_permalinks: false

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      