name: So Whats Bitcoin?
markdown: kramdown
timezone: America/Detroit
pygments: true
safe: true
lsi: false

url: http://www.sowhatsbitcoin.com
exclude:  [CNAME, Gemfile, Gemfile.lock, '*.less', gruntfile.js, custom_css, node_modules, README.md, '*.svg']
include: [glyphicons-halflings-regular.svg]

relative_permalinks: false

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      