name: So Whats Bitcoin?
markdown: kramdown
timezone: America/Detroit
pygments: true
safe: true
lsi: false

url: http://www.sowhatsbitcoin.com
exclude:  [CNAME, Gemfile, Gemfile.lock]

relative_permalinks: false

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      